//
//  faqList.swift
//  Tee's Shoes
//
//  Created by Smartcodes on 22/11/2021.
//

let questions = [
    Faq(title: "How Can I Pay With Mpesa?", par1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore ", par2: "Sed finibus, tortor a facilisis euismod, quam ligula efficitur sem, in sagittis enim lorem ac lectus. Suspendisse potenti. In dapibus suscipit magna, sit amet dignissim diam consequat vel. Nam tristique in lorem eu sodales. Sed rhoncus facilisis tortor et volutpat. Phasellus fringilla ligula sed ligula semper posuere. Vestibulum quis facilisis sem. Praesent sit amet metus sit amet tortor vestibulum iaculis. Ut pulvinar varius nisi at vehicula. Morbi porttitor neque augue, quis rutrum diam pretium eget. Mauris tristique leo elit, mattis sodales massa sollicitudin ac. Mauris auctor augue in varius ultricies. Vivamus eu massa cursus, porta justo vel, volutpat nunc. Aliquam condimentum nisl a felis auctor, in pulvinar nisi tempus. Phasellus sem nunc, varius ut dolor id, venenatis aliquam arcu."),
    Faq(title: "How to Order In Bulk", par1: "Aenean ut augue interdum mauris accumsan ultricies. Aenean scelerisque enim eu sapien mattis, a elementum libero placerat. Nam lectus diam, iaculis nec augue eget, efficitur pellentesque diam. Ut pellentesque sed ex at ultricies. Ut rhoncus turpis at gravida mollis. Etiam eget libero finibus, pellentesque elit in, auctor leo. In hac habitasse platea dictumst. Morbi eget sem ac felis bibendum suscipit eget quis lectus. Curabitur ac felis at neque faucibus fringilla ac at dui. Curabitur sit amet odio at tortor malesuada molestie ac at lectus.", par2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore "),
    Faq(title: "Can I Get Refunds Or Exchange", par1: "Aenean pharetra nibh id eros feugiat auctor. Vivamus porttitor sed ipsum vulputate auctor. Sed nec turpis vestibulum, tincidunt diam ac, egestas orci. Aliquam et dolor arcu. Sed quis vehicula elit, nec tempus neque. Cras at urna ultrices, rutrum orci in, scelerisque felis. Etiam enim turpis, suscipit in posuere non, ultrices id nulla.", par2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore "),
    Faq(title: "How Can I Pay without A Credit?", par1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore ", par2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore "),
    Faq(title: "How Long Does Delivery Take? ", par1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore ", par2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore "),
    Faq(title: "What Locations Do You Deliver To?", par1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore ", par2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore ")]
struct Faq{
    let title : String
    let par1 : String
    let par2: String
}
